# Site settings
title: Jialuo's Gallery
description: You can stay in my garden
baseurl: "ga_blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Jialuo


# Google Analytics
google_analytics: 56900809-X
# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
